// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvFjnS1uavrhnEgAofdbBX9uc72fZxXXA',
    appId: '1:199244171546:web:29a7b2261f163e9e6084a3',
    messagingSenderId: '199244171546',
    projectId: 'flutter-firebase-third-a-55b3a',
    authDomain: 'flutter-firebase-third-a-55b3a.firebaseapp.com',
    storageBucket: 'flutter-firebase-third-a-55b3a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaI0EtGQnO-mTpMHJcvBZdYvOyUKcy4yk',
    appId: '1:199244171546:android:7ee28c275a32ff6a6084a3',
    messagingSenderId: '199244171546',
    projectId: 'flutter-firebase-third-a-55b3a',
    storageBucket: 'flutter-firebase-third-a-55b3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqJoAijlV0ole1dcCNn_sjZUY3HHaYGuc',
    appId: '1:199244171546:ios:34d5093fb9d41e1a6084a3',
    messagingSenderId: '199244171546',
    projectId: 'flutter-firebase-third-a-55b3a',
    storageBucket: 'flutter-firebase-third-a-55b3a.appspot.com',
    iosClientId: '199244171546-3lmonp7qcf9n6bv7biaqd4vc7auss2e6.apps.googleusercontent.com',
    iosBundleId: 'com.example.thirdApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqJoAijlV0ole1dcCNn_sjZUY3HHaYGuc',
    appId: '1:199244171546:ios:34d5093fb9d41e1a6084a3',
    messagingSenderId: '199244171546',
    projectId: 'flutter-firebase-third-a-55b3a',
    storageBucket: 'flutter-firebase-third-a-55b3a.appspot.com',
    iosClientId: '199244171546-3lmonp7qcf9n6bv7biaqd4vc7auss2e6.apps.googleusercontent.com',
    iosBundleId: 'com.example.thirdApp',
  );
}
