// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjP134dfcSa9b3zLty9LxTlPWvZbSx8ns',
    appId: '1:502665154779:web:e1392f7c52083212a47cfe',
    messagingSenderId: '502665154779',
    projectId: 'flutter-firebase-third-app',
    authDomain: 'flutter-firebase-third-app.firebaseapp.com',
    storageBucket: 'flutter-firebase-third-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2AykNl5bnXBoKvf40GCgQToTfK5OmOcc',
    appId: '1:502665154779:android:af6869e077142799a47cfe',
    messagingSenderId: '502665154779',
    projectId: 'flutter-firebase-third-app',
    storageBucket: 'flutter-firebase-third-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC82zAQQrQ_cwvLPKxjRsyHR8kAYxoWuQw',
    appId: '1:502665154779:ios:ffd6f2d6fd17f685a47cfe',
    messagingSenderId: '502665154779',
    projectId: 'flutter-firebase-third-app',
    storageBucket: 'flutter-firebase-third-app.appspot.com',
    iosClientId: '502665154779-e85ms4vil5o18sumtaaigt80noq8bgg8.apps.googleusercontent.com',
    iosBundleId: 'com.example.thirdApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC82zAQQrQ_cwvLPKxjRsyHR8kAYxoWuQw',
    appId: '1:502665154779:ios:ffd6f2d6fd17f685a47cfe',
    messagingSenderId: '502665154779',
    projectId: 'flutter-firebase-third-app',
    storageBucket: 'flutter-firebase-third-app.appspot.com',
    iosClientId: '502665154779-e85ms4vil5o18sumtaaigt80noq8bgg8.apps.googleusercontent.com',
    iosBundleId: 'com.example.thirdApp',
  );
}
