// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7i9vA5uFO4LHLbYhKaHZTOgck5G3-_-Y',
    appId: '1:485021477859:web:62d9e2bff09302107bced6',
    messagingSenderId: '485021477859',
    projectId: 'fir-flutter-third-app',
    authDomain: 'fir-flutter-third-app.firebaseapp.com',
    storageBucket: 'fir-flutter-third-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkwEsbEUVAH9lMGxHffk1Dqjg5KUTz3io',
    appId: '1:485021477859:android:62f358bb35b6af487bced6',
    messagingSenderId: '485021477859',
    projectId: 'fir-flutter-third-app',
    storageBucket: 'fir-flutter-third-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1RWfn0CaJbn_LzoLwoZ1Xc_IUNIAQiSw',
    appId: '1:485021477859:ios:e6aa5dc31e5f99407bced6',
    messagingSenderId: '485021477859',
    projectId: 'fir-flutter-third-app',
    storageBucket: 'fir-flutter-third-app.appspot.com',
    iosClientId: '485021477859-ug04lt7hjn0smf6b42l1nvs5uarnkdgi.apps.googleusercontent.com',
    iosBundleId: 'com.example.thirdApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1RWfn0CaJbn_LzoLwoZ1Xc_IUNIAQiSw',
    appId: '1:485021477859:ios:e6aa5dc31e5f99407bced6',
    messagingSenderId: '485021477859',
    projectId: 'fir-flutter-third-app',
    storageBucket: 'fir-flutter-third-app.appspot.com',
    iosClientId: '485021477859-ug04lt7hjn0smf6b42l1nvs5uarnkdgi.apps.googleusercontent.com',
    iosBundleId: 'com.example.thirdApp',
  );
}
